name: file_converter
description: "Image to PDF Converter & Image Resizer - Convert images to PDF with DPI control and size optimization"
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.2

  # Image Handling
  image_picker: ^1.1.2
  image: ^4.3.0
  flutter_image_compress: ^2.4.0
  platform_image_converter: ^0.2.0

  # PDF Generation
  pdf: ^3.11.1
  printing: ^5.13.3

  # Drag & Drop Reordering
  reorderable_grid_view: ^2.2.8

  # Local Storage
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  sqflite: ^2.3.0
  path: ^1.8.3

  # Ads
  google_mobile_ads: ^5.2.0

  # In-App Purchases
  in_app_purchase: ^3.2.0

  # Utils
  uuid: ^4.5.1
  permission_handler: ^11.3.1
  file_picker: ^8.1.6
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.2.1
  share_plus: ^12.0.1
  open_filex: ^4.7.0
  tutorial_coach_mark: ^1.2.11
  media_store_plus: ^0.1.3
  gal: ^2.3.2
  url_launcher: ^6.3.0
  in_app_review: ^2.0.9
  google_mlkit_text_recognition: ^0.15.1
  intl: ^0.20.2
  cunning_document_scanner: ^1.2.3
  flutter_launcher_icons: ^0.14.4
  device_info_plus: ^11.3.0
  syncfusion_flutter_pdf: ^33.1.49


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  flutter_native_splash: ^2.4.0
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#0F172A" # Dark blue background (AppColors.backgroundDark)
  image: "assets/icon/app_icon.png"
  branding: "assets/icon/app_icon.png"
  color_dark: "#0F172A"
  image_dark: "assets/icon/app_icon.png"
  branding_dark: "assets/icon/app_icon.png"

  android_12:
    image: "assets/icon/app_icon.png"
    icon_background_color: "#0F172A"
    image_dark: "assets/icon/app_icon.png"
    icon_background_color_dark: "#0F172A"


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700